<div class="options-list__item -current-file">
	<div class="options-list-link__inner-wrap">
		<div class="options-list__icon">
			<div class="icon-file-evernote"></div>
		</div>
		<div class="options-list__text-wrap">
			<a href="#" class="options-list__text options-list__text--current-file">current_file_with_a_very_long_name_which_cant_fit_on_the_screen.doc</a>
		</div>
		<div class="options-list__icon -right">
			<div class="icon-gdrive-sml"></div>
		</div>
	</div>
</div>
