<header class="panel-header panel-header--location">
	<div class="media -v-center">
	    <div class="media__img pop-menu-trigger js-pmt js-tt" 
	    	data-tt="Change Source"
	    	data-tt-dir="right"
	    	data-pop-menu="sources"
	    	>
	    	<div class="icon__gdrive"></div>
	    </div>
	    <div class="media__body">
	    	<div class="split-view__heading">My Drive</div>
	    </div>
	</div>
</header>
