<header class="panel-header -stage">

	{% include "stage-heading.swig" %}
	{% include "stage-account-nav.swig" %}
	{% include "stage-nav.swig" %}

	<div class="search-field-wrap js-search-field-wrap">
		<input 
			type="text" 
			class="search-field js-search-field" 
			name="name" 
			placeholder="Search Gluru">
		<div class="search-field-icon icon__search--dark js-search"></div>
	</div>


</header>
