<nav class="stage-nav -account">
	<ul class="stage-nav__list">
		<li class="stage-nav__item -now">
			<div class="stage-nav__icon-wrap js-now">
				<div class="text">Now</div>
				<div class="icon-now-white"></div>
			</div>
		</li>
		<li class="stage-nav__item -notifications">
			<div class="stage-nav__icon-wrap">
				<div class="icon-notifications-white"></div>
				<div class="inset-num">5</div>
			</div>
		</li>
	</ul>
</nav>
