{% set obj_stage_data = obj.sections[0].stage_data %}
{% include "stage-start.swig" %}
{% include "panel-header-stage.swig" %}

{% set obj_setup_data = obj.sections[0] %}

{# section signup #}
    
    <header class="panel-header panel-header--setup">
        <nav class="header-nav -setup">
            <ul class="header-nav__list">
                
            </ul>
        </nav>
    </header>

    <div class="scrollable-content__wrap -stage">
        <div class="scrollable-content">


    <div class="island content">

        <div class="island promo">island promo</div>

    </div>

    <div class="island sub-content">
      
        <div class="island twitter">island twitter</div>
      
    </div>
                        
{% include "stage__setup--end.swig" %}

{% include "stage-end.swig" %}
